# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: research
    weight: 10
    identifier: research
  - name: Projects
    url: '/research/#projects'
    weight: 20
    parent: research
  - name: Publications
    url: '/research/#publications'
    weight: 30
    parent: research
  - name: Education
    url: education
    weight: 100
    identifier: education
  - name: MSc Thesis
    url: mscthesis
    weight: 200
  - name: News
    url: '/news'
    weight: 300
  - name: About SNAIL
    url: '/about'
    weight: 400
    identifier: about
  - name: About
    url: '/about'
    weight: 410
    parent: about
  - name: Contact
    url: '/about/#contact'
    weight: 420
    parent: about
  - name: People
    url: '/people'
    weight: 430
    parent: about
