# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: research
    weight: 10
    identifier: research
  - name: Projects
    url: '/research/#projects'
    weight: 20
    parent: research
  - name: Publications
    url: '/research/#publications'
    weight: 30
    parent: research
  - name: MSc Thesis
    url: mscthesis
    weight: 40
  - name: About SNAIL
    url: '/aboutsnail/#about'
    weight: 50
    identifier: aboutsnail
  - name: About
    url: '/aboutsnail/#about'
    weight: 60
    parent: aboutsnail
  - name: News
    url: '/aboutsnail/#news'
    weight: 70
    parent: aboutsnail
  - name: Contact
    url: '/aboutsnail/#contact'
    weight: 80
    parent: aboutsnail
  - name: People
    url: '/people'
    weight: 90
    parent: aboutsnail
